### ISSUE TITLE
Does <T> need to be Default?

### ISSUE THREAD

**Issue by lv10wizard** [tpisto/fuzzy_prefix_search#1]
Hi,

Does `T` need to be bounded by the `Default` trait?

<details><summary>
<s>It seems like two main code changes can be made to drop the `Default` requirement (aside from removing various `Default` keywords):</s>
</summary>

```diff
--- a/src/trie.rs
+++ b/src/trie.rs
@@ -75,7 +75,7 @@ impl<T: Clone + Default + PartialEq + Eq + Hash + Debug> TrieData<T> {
         node.data.push(data.clone());
         node.is_end = true;
 
-        self.data_map.entry(data).or_default().push(current);
+        self.data_map.entry(data).or_insert_with(|| vec![]).push(current);
     }
 
     /// Searches for words within a given edit distance or starting with the given prefix.
```

```diff
--- a/src/trie.rs
+++ b/src/trie.rs
@@ -323,7 +323,7 @@ impl<T: Clone + Default + PartialEq + Eq + Hash + Debug> Trie<T> {
         Trie {
             trie_data: Arc::new(RwLock::new(TrieData {
                 root: TrieNode::new(),
-                data_map: HashMap::default(),
+                data_map: HashMap::new(),
             })),
         }
     }
```
</details>

*edit:* Actually, it seems like just removing the `Default` keyword from various trait bounds is enough to drop the requirement since `Trie` does not need to construct a `T` anywhere, but maybe I've missed something?

I can submit a pull request if you prefer.

Or if you disagree with these changes, that's fine too. (or if there's some performance penalty or unintended consequence I'm unaware of)

### Motivation

I want to store [`indextree`](https://docs.rs/indextree/latest/indextree/index.html)`::`[`NodeId`](https://docs.rs/indextree/latest/src/indextree/id.rs.html#21-33)s in a `Trie` but they aren't `Default`.

**Comment by tpisto** [comment]
Thank you for your message! I just published new version where I removed the Default bounds 👍🏻
